services:
  - type: web
    name: style-tehran-shirt-frontend
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
    staticPublishPath: dist
